# Generated by Django 3.2.3 on 2023-11-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0004_auto_20231113_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_levels',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='interested',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
